/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.showcase.v1beta1.it.logging;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.spi.ILoggingEvent;
import com.google.api.gax.rpc.ApiException;
import com.google.api.gax.tracing.LoggingTracer;
import com.google.showcase.v1beta1.EchoClient;
import com.google.showcase.v1beta1.FailEchoWithDetailsRequest;
import com.google.showcase.v1beta1.it.util.TestClientInitializer;
import java.lang.reflect.Method;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.slf4j.LoggerFactory;
import org.slf4j.event.KeyValuePair;

public class ITActionableErrorsLogging {

  private static EchoClient grpcClient;
  private static EchoClient httpjsonClient;

  @BeforeAll
  static void createClients() throws Exception {
    com.google.api.gax.logging.LoggingUtils.setLoggingV2Enabled(true);
    // Create gRPC Echo Client
    grpcClient = TestClientInitializer.createGrpcEchoClient();
    // Create Http JSON Echo Client
    httpjsonClient = TestClientInitializer.createHttpJsonEchoClient();
  }

  @AfterAll
  static void destroyClients() throws InterruptedException {
    grpcClient.close();
    httpjsonClient.close();

    grpcClient.awaitTermination(TestClientInitializer.AWAIT_TERMINATION_SECONDS, TimeUnit.SECONDS);
    httpjsonClient.awaitTermination(
        TestClientInitializer.AWAIT_TERMINATION_SECONDS, TimeUnit.SECONDS);
    com.google.api.gax.logging.LoggingUtils.setLoggingV2Enabled(false);
  }

  private TestAppender setupTestLogger() {
    TestAppender testAppender = new TestAppender();
    testAppender.start();
    org.slf4j.Logger logger = LoggerFactory.getLogger(LoggingTracer.class);
    ((ch.qos.logback.classic.Logger) logger).setLevel(Level.INFO);
    ((ch.qos.logback.classic.Logger) logger).addAppender(testAppender);
    return testAppender;
  }

  @Test
  void testGrpc_actionableErrorLogged() {
    TestAppender testAppender = setupTestLogger();

    FailEchoWithDetailsRequest request = FailEchoWithDetailsRequest.newBuilder().build();

    ApiException exception = assertThrows(ApiException.class, () -> grpcClient.failEchoWithDetails(request));

    assertThat(testAppender.events.size()).isAtLeast(1);
    ILoggingEvent loggingEvent = testAppender.events.get(testAppender.events.size() - 1);
    
    assertThat(loggingEvent.getLevel()).isEqualTo(Level.INFO);
    assertThat(loggingEvent.getMessage()).contains("This is an error generated by the server");
    
    List<KeyValuePair> kvps = loggingEvent.getKeyValuePairs();
    assertThat(kvps).contains(new KeyValuePair("rpc.system.name", "grpc"));
    assertThat(kvps).contains(new KeyValuePair("rpc.method", "google.showcase.v1beta1.Echo/FailEchoWithDetails"));
    assertThat(kvps).contains(new KeyValuePair("rpc.response.status_code", "ABORTED"));
    assertThat(kvps).contains(new KeyValuePair("error.type", "some ErrorInfo reason"));
    assertThat(kvps).contains(new KeyValuePair("gcp.errors.domain", ""));

    testAppender.stop();
  }

  @Test
  void testHttpJson_actionableErrorLogged() {
    TestAppender testAppender = setupTestLogger();

    FailEchoWithDetailsRequest request = FailEchoWithDetailsRequest.newBuilder().build();

    ApiException exception = assertThrows(ApiException.class, () -> httpjsonClient.failEchoWithDetails(request));

    assertThat(testAppender.events.size()).isAtLeast(1);
    ILoggingEvent loggingEvent = testAppender.events.get(testAppender.events.size() - 1);
    
    assertThat(loggingEvent.getLevel()).isEqualTo(Level.INFO);
    assertThat(loggingEvent.getMessage()).isNotNull();
    
    List<KeyValuePair> kvps = loggingEvent.getKeyValuePairs();
    assertThat(kvps).contains(new KeyValuePair("rpc.system.name", "http"));
    assertThat(kvps).contains(new KeyValuePair("rpc.method", "google.showcase.v1beta1.Echo/FailEchoWithDetails"));
    assertThat(kvps).contains(new KeyValuePair("rpc.response.status_code", "ABORTED"));

    testAppender.stop();
  }
}
